# уникальный ключ проекта на сервере SonarQube
sonar.projectKey=SerLib1C

# имя проекта на сервере SonarQube
sonar.projectName=SerLib1C

# версия исходников проекта
sonar.projectVersion=1.0

# Относительный путь к исходникам. Замените "\" на "/" при запуске на Windows.
# Если не указано, SonarQube будет искать исходный код начиная с каталога, содержащего файл sonar-project.properties.
sonar.sources=./dp

# Относительный путь к тестам.
# sonar.tests=./tests

# тип системы контроля версий
sonar.scm.provider=git

# маска поиска файлов на проверку
sonar.inclusions=**/*.bsl,**/*.mdo,**/*.form,**/*.dcss,**/*.xml

# маска поиска исключений файлов на проверку
sonar.exclusions=**/*.html,**/Template.mxlx,**/Templates/**/*.mxlx,**/CommonPictures/**/*.*
sonar.lang.patterns.xml=**/*.xsd,**/*.xsl

# Кодировка исходного кода. По умолчанию используется системная кодировка.
sonar.sourceEncoding=UTF-8

sonar.ws.timeout=300
sonar.qualitygate.wait=false
sonar.qualitygate.timeout=300

# Путь к отчету о покрытии тестами
# sonar.coverageReportPaths=coverage/genericCoverage.xml

# Путь к отчету о выполнении тестов
# sonar.testExecutionReportPaths=test-reports/tests.xml